[phases.setup]
# Ensure python + pip exist in the build image
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = [
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "gunicorn JJI.wsgi --bind 0.0.0.0:$PORT"